// Admin
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

// Administrators
export const ADMINISTRATORS = "ADMINISTRATORS";
export const ADMINISTRATORS_FILTERS = "ADMINISTRATORS_FILTERS";
export const ONE_ADMINISTRATOR = "ONE_ADMINISTRATOR";
export const CLEAR_ONE_ADMINISTRATOR = "CLEAR_ONE_ADMINISTRATOR";
export const CREATE_ADMINISTRATOR = "CREATE_ADMINISTRATOR";
export const EDIT_ADMINISTRATOR = "EDIT_ADMINISTRATOR";
export const DELETE_ADMINISTRATOR = "DELETE_ADMINISTRATOR";

// Donations
export const DONATIONS = "DONATIONS";
export const ONE_DONATION = "ONE_DONATION";
export const CLEAR_ONE_DONATION = "CLEAR_ONE_DONATION";
export const DONATIONS_FILTERS = "DONATIONS_FILTERS";
export const REACTIVE_DONATION = "REACTIVE_DONATION";
export const REMOVE_DONATION = "REMOVE_DONATION";
export const DELETE_DONATION = "DELETE_DONATION";
export const CREATE_DONATION = "DELETE_DONATION";
export const ADD_ITEMS = "ADD_ITEMS";
// Gallery
export const GALLERY = "GALLERY";
export const GALLERY_FILTERS = "GALLERY_FILTERS";
export const ONE_GALLERY = "ONE_GALLERY";
export const CLEAR_ONE_GALLERY = "CLEAR_ONE_GALLERY";
export const CREATE_GALLERY = "CREATE_GALLERY";
export const EDIT_GALLERY = "EDIT_GALLERY";
export const EDIT_GALLERY_FORM = "EDIT_GALLERY_FORM";
export const REACTIVE_GALLERY = "REACTIVE_GALLERY";
export const REMOVE_GALLERY = "REMOVE_GALLERY";
export const DELETE_GALLERY = "DELETE_GALLERY";

// News
export const NEWS = "NEWS";
export const NEW_DETAIL = "NEWS_DETAIL";
export const CLEAR_NEW_DETAIL = "CLEAR_NEWS_DETAIL";
export const NEWS_FILTERS = "NEWS_FILTERS";
export const CREATE_NEW = "CREATE_NEW";
export const EDIT_NEW = "EDIT_NEW";
export const EDIT_NEW_FORM = "EDIT_NEW_FORM";
export const REACTIVE_NEW = "REACTIVE_NEW";
export const REMOVE_NEW = "REMOVE_NEW";
export const DELETE_NEW = "DELETE_NEW";

// Our Works
export const OUR_WORKS = "OUR_WORKS";
export const OUR_WORKS_FILTERS = "OUR_WORKS_FILTERS";
export const ONE_WORK = "ONE_WORK";
export const CLEAR_ONE_WORK = "CLEAR_ONE_WORK";
export const CREATE_NEW_WORK = "CREATE_NEW_WORK";
export const EDIT_WORK = "EDIT_WORK";
export const EDIT_WORK_FORM = "EDIT_WORK_FORM";
export const REACTIVE_WORK = "REACTIVE_WORK";
export const REMOVE_WORK = "REMOVE_WORK";
export const DELETE_WORK = "DELETE_WORK";

// Radio Program
export const RADIO_PROGRAM = "RADIO_PROGRAM";
export const RADIO_PROGRAM_FILTERS = "RADIO_PROGRAM_FILTERS";
export const ONE_RADIO_PROGRAM = "ONE_RADIO_PROGRAM";
export const CLEAR_ONE_RADIO_PROGRAM = "CLEAR_ONE_RADIO_PROGRAM";
export const CREATE_RADIO_PROGRAM = "CREATE_RADIO_PROGRAM";
export const EDIT_RADIO_PROGRAM = "EDIT_RADIO_PROGRAM";
export const EDIT_RADIO_PROGRAM_FORM = "EDIT_RADIO_PROGRAM_FORM";
export const REACTIVE_RADIO_PROGRAM = "REACTIVE_RADIO_PROGRAM";
export const REMOVE_RADIO_PROGRAM = "REMOVE_RADIO_PROGRAM";
export const DELETE_RADIO_PROGRAM = "DELETE_RADIO_PROGRAM";

// Subscriptions
export const SUBSCRIPTIONS = "SUBSCRIPTIONS";
export const ONE_SUBSCRIPTION = "ONE_SUBSCRIPTION";
export const CLEAR_ONE_SUBSCRIPTION = "SUBSCLEAR_ONE_CRIPTION";
export const SUBSCRIPTIONS_FILTERS = "SUBSCRIPTIONS_FILTERS";
export const DELETE_SUBSCRIPTION = "DELETE_SUBSCRIPTION";
